### ISSUE TITLE
audio2audio errors : `st.cache` is deprecated + missing 1 required positional argument: 'init_image' 

### ISSUE THREAD

**Issue by Katmoget** [riffusion/riffusion#156]
Hi

I get the following errors when trying to use audio-to-audio in playground :
----------------------------------------------------------------------------------
2023-10-28 09:30:37.155 `st.cache` is deprecated. Please use one of Streamlit's new caching commands,
`st.cache_data` or `st.cache_resource`.

More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
Fetching 15 files: 100%|...........................................| 15/15 [00:00<?, ?it/s]
You have passed a non-standard module <function load_stable_diffusion_img2img_pipeline.<locals>.<lambda> at 0x000001E19002FC70>. We cannot verify whether it has the correct type
2023-10-28 09:30:41.658 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 679, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 436, in _read_from_cache
    raise e
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 421, in _read_from_cache
    return _read_from_mem_cache(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 338, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\riffusion\riffusion\streamlit\playground.py", line 34, in <module>
    render()
  File "D:\riffusion\riffusion\streamlit\playground.py", line 29, in render
    module.render()
  File "D:\riffusion\riffusion\streamlit\tasks\audio_to_audio.py", line 272, in render
    image = streamlit_util.run_img2img(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 716, in wrapped_func
    return get_or_create_cached_value()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 697, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
  File "D:\riffusion\riffusion\streamlit\util.py", line 383, in run_img2img
    result = pipeline(
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionImg2ImgPipeline.__call__() missing 1 required positional argument: 'init_image'

----------------------------------------------------------------------------

Using magic mix : the files are created however I still get the cache error and it is extremely slow.

thanks

**Comment by 1044690543** [comment]
+1

**Comment by 1044690543** [comment]
pip install diffusers==0.10.0
