### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.pipeline_utils'

### ISSUE THREAD

**Issue by hfabio** [riffusion/riffusion#162]
I'm using WSL2 with Ubuntu 20.04.6 LTS
Using anaconda `23.3.1` and python `3.9.16`
- pulled main branch
- installed dependencies `pip install -r requirements.txt`
- ran `python -m riffusion.streamlit.playground`
- selected  `text-to-audio` and got this error:
```bash
2023-11-27 19:21:05.990 Uncaught app exception
Traceback (most recent call last):
  File "/home/hfabio/miniconda3/envs/python3/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/streamlit/playground.py", line 34, in <module>
    render()
  File "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/streamlit/playground.py", line 28, in render
    module = __import__(PAGES[page], fromlist=["render"])
  File "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/streamlit/tasks/text_to_audio.py", line 6, in <module>
    from riffusion.streamlit import util as streamlit_util
  File "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/streamlit/util.py", line 15, in <module>
    from riffusion.riffusion_pipeline import RiffusionPipeline
  File "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/riffusion_pipeline.py", line 14, in <module>
    from diffusers.pipeline_utils import DiffusionPipeline
ModuleNotFoundError: No module named 'diffusers.pipeline_utils'
/home/hfabio/miniconda3/envs/python3/lib/python3.9/site-packages/streamlit/watcher/local_sources_watcher.py:177: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  lambda m: [p for p in m.__path__._path],
```

I've tried reinstalling `diffusers` and didn't solve the problem
```bash
pip uninstall diffusers
pip install diffusers
pip install -r requirements.txt
```

**Comment by mysticallego** [comment]
changing the line in "/home/hfabio/Projetos/ai/riffusion/riffusion/riffusion/riffusion_pipeline.py" from
`from diffusers.pipeline_utils import DiffusionPipeline`
to
`from diffusers.pipelines.pipeline_utils import DiffusionPipeline`
worked for me I think
