### ISSUE TITLE
__init__() got an unexpected keyword argument 'max_iter'

### ISSUE THREAD

**Issue by wangjifly1** [riffusion/riffusion#166]
when i run a test as follows:
python -m unittest test.audio_to_image_test
an error happens:

Traceback (most recent call last):
  File "/Users/wangji/riffusion-main/test/audio_to_image_test.py", line 42, in test_stereo
    self.helper_test_with_params(params)
  File "/Users/wangji/riffusion-main/test/audio_to_image_test.py", line 60, in helper_test_with_params
    audio_to_image(audio=str(audio_path), image=str(image_path), **params)
  File "/Users/wangji/riffusion-main/riffusion/cli.py", line 54, in audio_to_image
    converter = SpectrogramImageConverter(params=params, device=device)
  File "/Users/wangji/riffusion-main/riffusion/spectrogram_image_converter.py", line 21, in __init__
    self.converter = SpectrogramConverter(params=params, device=device)
  File "/Users/wangji/riffusion-main/riffusion/spectrogram_converter.py", line 87, in __init__
    self.inverse_mel_scaler = torchaudio.transforms.InverseMelScale(
TypeError: __init__() got an unexpected keyword argument 'max_iter'

Many thanks for help！！

**Comment by wangjifly1** [comment]
I have solved this problem :
pip install --upgrade torch==2.0.1
pip install --upgrade torchaudio==2.0.1
pip install --upgrade torchvision==0.15.1

**Comment by Cryptospy** [comment]
same, TypeError: __init__() got an unexpected keyword argument 'max_iter'

**Comment by J4BEZ** [comment]
@Cryptospy It is due to the stable version of torchvision has been updated to 2.1.2,

InverseMelScale class in torchvision 2.0.1 has the keyword argument named 'max_iter'
but the version of 2.1.2 doesn't.

You can solve the problem easily with the [solution](https://github.com/riffusion/riffusion/issues/166#issuecomment-1859497737) that @wangjifly1 suggested for us.
:: downgrade version of torchvision

if you would be available for a second for me,
You may check it out in more detail through the PR that I wrote [ #165 ]


Hope you have a peaceful day and happy new year✨

**Comment by Cryptospy** [comment]
@J4BEZ  This worked for me:

pip uninstall torch torchaudio torchvision

pip install torch==2.0.1+cu118 torchaudio==2.0.2+cu118 torchvision==0.15.2+cu118 -f https://download.pytorch.org/whl/cu118/torch_stable.html

**Comment by Cryptospy** [comment]
@J4BEZ happy new year to you too mate

**Comment by J4BEZ** [comment]
@Cryptospy Happy to hear that😆😆
Hope you have a joyful weekend and happy new year🙌🙌

**Comment by winterer** [comment]
If downgrading torchaudio is not an option, the following code modification works for me (removal of unused parameters due to API changes in torchaudio 2.1.x):

``` diff
diff --git a/riffusion/spectrogram_converter.py b/riffusion/spectrogram_converter.py
index 9fbfc65..2beb605 100644
--- a/riffusion/spectrogram_converter.py
+++ b/riffusion/spectrogram_converter.py
@@ -90,10 +90,6 @@ class SpectrogramConverter:
             sample_rate=params.sample_rate,
             f_min=params.min_frequency,
             f_max=params.max_frequency,
-            max_iter=params.max_mel_iters,
-            tolerance_loss=1e-5,
-            tolerance_change=1e-8,
-            sgdargs=None,
             norm=params.mel_scale_norm,
             mel_scale=params.mel_scale_type,
         ).to(self.device)
```

**Comment by candlelightner** [comment]
If you choose to downgrade, you also have to install a compatible version of numpy: 

`python -m pip install "numpy<2"`
