### ISSUE TITLE
 assert torch.cuda.is_available() AssertionError

### ISSUE THREAD

**Issue by sjlynch** [riffusion/riffusion#3]
I'm having trouble running this. I followed the install steps and entered the following and got the resulting assertion error. I have no trouble running stable diffusion locally, so I'm not sure what to do next here. Install a newer version of CUDA toolkit? My GPU is a 3090.

python -m riffusion.server --port 3013 --host 127.0.0.1 --checkpoint ./

Traceback (most recent call last):
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Desktop\SD-GUI-1.3.1\riffusion\riffusion-inference-main\riffusion\server.py", line 215, in <module>
    argh.dispatch_command(run_app)
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\site-packages\argh\dispatching.py", line 306, in dispatch_command
    dispatch(parser, *args, **kwargs)
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "C:\Users\username\anaconda3\envs\riffusion-inference\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "C:\Users\username\Desktop\SD-GUI-1.3.1\riffusion\riffusion-inference-main\riffusion\server.py", line 59, in run_app
    MODEL = load_model(checkpoint=checkpoint)
  File "C:\Users\username\Desktop\SD-GUI-1.3.1\riffusion\riffusion-inference-main\riffusion\server.py", line 79, in load_model
    assert torch.cuda.is_available()
AssertionError

**Comment by Meatfucker** [comment]
The requirements.txt fails to pull in cuda. Youll need to install the proper cuda enabled torch version for your card.
Check out the torch website, they have a little configurator to make a command for you.

**Comment by sjlynch** [comment]
Thanks, it worked! New to python and ML so greatly appreciated!

**Comment by Aymendje** [comment]
@sjlynch 
Try running this :

```
pip install soundfile
pip install torch>=1.9.0+cu116 torchvision>=0.9.0+cu116 torchaudio>=0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by CJGuirao** [comment]
This worked for me in a 3090 
pip install torch===1.13.1+cu117 torchvision===0.14.1+cu117 torchaudio===0.13.1+cu117 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by DaemonAlchemist** [comment]
It would be helpful for the installation instructions to include and/or link to the guide for installing CUDA on your system.

**Comment by hmartiro** [comment]
I'd love for the requirements file to install torch with CUDA if compatible, but I haven't figured out exactly what to put. This thread might be helpful https://github.com/pytorch/pytorch/issues/34064

**Comment by hmartiro** [comment]
Closing as the README now has an improved guide
