### ISSUE TITLE
rriffusion.cli image-to-audio fails with - ValueError: axes don't match array 

### ISSUE THREAD

**Issue by eran-sefirot** [riffusion/riffusion#51]
Hello,

Thanks for this great work!

I am trying to run a basic script, taking a seed image provided in the repository:
python -m riffusion.cli image-to-audio --image ./seed_images/og_beat.png --audio clip.wav

however it fails with the following stack (I added some prints to further investigate):

`<PIL.PngImagePlugin.PngImageFile image mode=P size=512x512 at 0x7FC22A2CC610>
WARNING: Could not find spectrogram parameters in exif data. Using defaults.
<PIL.Image.Image image mode=P size=512x512 at 0x7FC236F01C10>
np.array(image):
[[59 64 61 ... 59 64 61]
 [55 64 64 ... 55 64 64]
 [35 49 61 ... 35 49 61]
 ...
 [45 52 52 ... 45 52 52]
 [62  2 65 ... 62  2 65]
 [ 0  1  2 ...  0  1  2]]
Traceback (most recent call last):
  File "/opt/conda/envs/riffusion/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/riffusion/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/Sefi/riffusion/riffusion/cli.py", line 133, in <module>
    argh.dispatch_commands(
  File "/opt/conda/envs/riffusion/lib/python3.9/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/conda/envs/riffusion/lib/python3.9/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/conda/envs/riffusion/lib/python3.9/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/conda/envs/riffusion/lib/python3.9/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/ubuntu/Sefi/riffusion/riffusion/cli.py", line 88, in image_to_audio
    segment = converter.audio_from_spectrogram_image(pil_image)
  File "/home/ubuntu/Sefi/riffusion/riffusion/spectrogram_image_converter.py", line 79, in audio_from_spectrogram_image
    spectrogram = image_util.spectrogram_from_image(
  File "/home/ubuntu/Sefi/riffusion/riffusion/util/image_util.py", line 88, in spectrogram_from_image
    data = np.array(image).transpose(2, 0, 1)
ValueError: axes don't match array`

What am I missing?

**Comment by hmartiro** [comment]
Thanks for the report @eran-sefirot. The seed images were stored as single channel, which the tool didn't handle gracefully. Added a fix. But if you were to run it on an RGB image like in the `test/test_data` directory it would already work
