### ISSUE TITLE
Could use guidance on how to train

### ISSUE THREAD

**Issue by dustyny** [riffusion/riffusion#53]
I have a highly curated data set with hundreds of thousands of wav files that I was using for experimenting with using a GAN to generate audio. Recently I created a technique where I translate machine generated data into natural language text for a Diffusion model. 

I've been reading on the Discord server but I'm not 100% sure I got things figured out.. 

Here's what I'm thinking so far, please correct me where I am making mistakes. 

- Use the CLI to convert the wav files to spectrograms
- Generate my text prompts for using my python machine data to natural language text script; save to json for Dreambooth training
- Use the normal Dreambooth training process to fine tune on my audio data
-  Use the diffusion model to generate an spectrogram 
-  Use the CLI to convert the spectrogram to a wav file

Things I'm unclear on
- _I'm not sure if this model can be imported into Riffusion_
-  _If the model can't be imported into Riffusion, I should be able to do inferencing in a notebook like Automatic1111_
- _Unclear if ImgToImg, in & out painting can be used_
-_I have hundreds of thousands of wav files that I can label automatically, can/should I scale it this high, what is reasonable vs unreasonable_

**Comment by hmartiro** [comment]
Hey @dustyny! Yes you can use any standard training or dreambooth method as long as you have compatible spectrogram images with text. And you can use the CLI example to help convert with your desired parameters. Whether you fine tune or use dreambooth depends on how much data you have, typically dreambooth is for a much smaller dataset than hundreds of thousands of files.

The model can be imported into riffusion, and you can use it within automatic1111 (an extension to convert to audio also exists). Img2img, outpainting, and so on all work.

**Comment by hmartiro** [comment]
I'd be keen to hear about your use case if you DM me on discord as well.

**Comment by dustyny** [comment]
I really appreciate the response, I'll connect with you on discord to discuss more in depth. It sounds like standard training (I want to understand what you mean by that) is my best approach, I have a lot of data that I can use for training.

**Comment by jbmaxwell** [comment]
I got fine-tuning to run using the `examples/train_text_to_image.py` script in `diffusers`. You do need to format your data, but that's in the HF docs so not a huge issue.
In my case I had to download the riffusion model—I was getting errors when trying to get it directly from HF (i.e., in code). So I used git to download a local copy (you need `lfs`—also covered in the model card page).

The problem I'm having is that, when trying to run the fine-tuned model, I get a type error: `RuntimeError: Input type (c10::Half) and bias type (float) should be the same`
This is happening in `F.conv2d()`. Full trace:

```
Traceback (most recent call last):
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/james/src/somms/riffusion/riffusion/streamlit/pages/text_to_audio.py", line 102, in <module>
    render_text_to_audio()
  File "/home/james/src/somms/riffusion/riffusion/streamlit/pages/text_to_audio.py", line 78, in render_text_to_audio
    image = streamlit_util.run_txt2img(
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 428, in wrapper
    return get_or_create_cached_value()
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 401, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "/home/james/src/somms/riffusion/riffusion/streamlit/util.py", line 103, in run_txt2img
    output = pipeline(
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 531, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 421, in forward
    sample = self.conv_in(sample)
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/james/anaconda3/envs/riffusion/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```

Any thoughts as to what might be going on?
