### ISSUE TITLE
Ram requirements?

### ISSUE THREAD

**Issue by Meatfucker** [riffusion/riffusion#7]
I have attempted to get this project running on an Ubuntu machine with a M40, as well as a windows machine with a 3090, and on both when I try to run the inference server it fills up system ram and then crashes. Both machines have 32gb of system ram. 

It does not seem to be loading the gpu memory at all.

`(riffusion) PS C:\incoming\ml\riffusion-inference> python -m riffusion.server --port 3013 --host 127.0.0.1 --checkpoint .\riffusion-model-v1.ckpt
Traceback (most recent call last):
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\diffusers\configuration_utils.py", line 380, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\diffusers\configuration_utils.py", line 480, in _dict_from_json_file
    text = reader.read()
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\incoming\ml\riffusion-inference\riffusion\server.py", line 215, in <module>
    argh.dispatch_command(run_app)
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\argh\dispatching.py", line 306, in dispatch_command
    dispatch(parser, *args, **kwargs)
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "C:\incoming\ml\riffusion-inference\riffusion\server.py", line 59, in run_app
    MODEL = load_model(checkpoint=checkpoint)
  File "C:\incoming\ml\riffusion-inference\riffusion\server.py", line 81, in load_model
    model = RiffusionPipeline.from_pretrained(
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\diffusers\pipeline_utils.py", line 454, in from_pretrained
    config_dict = cls.load_config(
  File "C:\Users\Meatfucker\anaconda3\envs\riffusion\lib\site-packages\diffusers\configuration_utils.py", line 382, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '.\riffusion-model-v1.ckpt' is not a valid JSON file.
(riffusion) PS C:\incoming\ml\riffusion-inference>`

**Comment by jparmstr** [comment]
I figured out that it expects a folder with the entire contents of their HuggingFace project to be passed as the --checkpoint argument, otherwise it fills up the RAM like you said and crashes. You can clone everything into a folder like:

`git clone https://huggingface.co/riffusion/riffusion-model-v1`

I had to manually replace the riffusion-model-v1.ckpt file which failed to download properly. After doing that the server actually starts, but now I'm facing another error: "Not Found. The requested URL was not found on the server." and the command prompt is showing 404 errors.

**Comment by jparmstr** [comment]
Update: I made further progress and actually got it working.

You also need to install the project from https://github.com/hmartiro/riffusion-app and run it simultaneously with this one. Create an .env.local file as described in the riffusion-app's readme. With both riffusion-inference and riffusion-app running and talking to each other you'll get a locally running interface like their website, accessible at http://127.0.0.1:3000

**Comment by Meatfucker** [comment]
I also got it working though I would add that make sure you are explicit in your .env.local file. I used localhost and it attempted to use ::1 (an ipv6 localhost address) and it failed. Worked fine when I was explicit with 127.0.0.1

**Comment by Trev57** [comment]
I had the same issue with cloning the huggingface repo, it actually bluescreened my computer. if you use GIT_LFS_SKIP_SMUDGE=1, it clones without downloading the checkpoint, if you run the server, it tells you "OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned" currently its downloading so hopefully it doesnt crash.
