### ISSUE TITLE
[Playground] Index error on simultaneous access in audio_to_audio

### ISSUE THREAD

**Issue by hmartiro** [riffusion/riffusion#73]
cc @SethForsgren

**Comment by prescience-data** [comment]
Possibly related:
```
2023-01-07 15:06:36.385 MediaFileHandler: Missing file 868e105203ef0e8ff50fbb1cfc58d69c3975b3e458d787210552ffd0.wav
2023-01-07 15:06:53.103 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\***\anaconda3\envs\riffusion\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "D:\StableDiffusion\riffusion\riffusion\streamlit\pages\audio_to_audio.py", line 275, in <module>
    render_audio_to_audio()
  File "D:\StableDiffusion\riffusion\riffusion\streamlit\pages\audio_to_audio.py", line 257, in render_audio_to_audio
    combined_segment = result_segments[0]
IndexError: list index out of range
```
