### ISSUE TITLE
[AudioSplitter] Throws `WinError 2` when run

### ISSUE THREAD

**Issue by prescience-data** [riffusion/riffusion#76]
Not sure if this is a missing dependency or a Windows specific issue, but when I attempt to run the splitter my local throws: 

```
Traceback (most recent call last):
  File "C:\Users\***\anaconda3\envs\riffusion\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "D:\StableDiffusion\riffusion\riffusion\streamlit\pages\split_audio.py", line 80, in <module>
    render_split_audio()
  File "D:\StableDiffusion\riffusion\riffusion\streamlit\pages\split_audio.py", line 57, in render_split_audio
    stems = split_audio(segment, device=device)
  File "D:\StableDiffusion\riffusion\riffusion\audio_splitter.py", line 51, in split_audio
    subprocess.run(
  File "C:\Users\***\anaconda3\envs\riffusion\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\***\anaconda3\envs\riffusion\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\***\anaconda3\envs\riffusion\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by prescience-data** [comment]
Fix: https://github.com/facebookresearch/demucs/blob/main/docs/windows.md


```py
conda install -c conda-forge ffmpeg
python.exe -m pip install -U demucs PySoundFile
```

**Comment by hmartiro** [comment]
@prescience-data I've added pysoundfile back into the pip requirements. If you feel up to it, would be sweet to add windows CI to https://github.com/riffusion/riffusion/blob/main/.github/workflows/ci.yml
